spring.application.name=CampusEventManagement
# ===== Database Config =====
spring.datasource.url=jdbc:postgresql://localhost:5432/campusevents
spring.datasource.username=postgres
spring.datasource.password=titus

# ===== JPA Config =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Server Config =====
server.port=8080
