spring.application.name=CampusEventManagement
# ===== Database Config =====
spring.datasource.url=jdbc:postgresql://localhost:5432/campusevents
spring.datasource.username=postgres
spring.datasource.password=titus

# ===== JPA Config =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Server Config =====
server.port=8080

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=titusmucyo693@gmail.com
spring.mail.password=mygp ppxf pnuh gakn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# # JWT Configuration
# jwt.secret=CmgqhmjmIwH2rNEeuxW3cX3GB+ywUXV5VAoJY71LWFDfnvIyGN3FGV5Fvbn7VBEKYSKkULH5poXTQFI1hkKEfg==
# jwt.expiration=86400000

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB
